const StatusTransaction = () => {
  return (
    <div
      className="
         fixed rounded-b-2xl
         top-14
         right-0
         left-52
         grid grid-cols-1
         sm:grid-cols-2
         lg:grid-cols-4
         p-4
         gap-4
         pb-5
         bg-white
       "
    >
      <div
        className="
           bg-white
           shadow-lg
           rounded-lg
           flex
           items-center
           justify-between
           p-3
           text-white
           font-medium
           group
         "
      >
        <div
          className="
             flex
             justify-center
             items-center
             w-14
             h-14
             bg-blue-50
             rounded-full
             transition-all
             duration-300
             transform
             group-hover:rotate-12
           "
        >
          <i class="fas fa-utensils text-blue-500 text-2xl"></i>
        </div>
        <div className="text-right text-gray-700">
          <p className="text-2xl">1,257</p>
          <p>Foods</p>
        </div>
      </div>
      <div
        className="
           bg-white
           shadow-lg
           rounded-lg
           flex
           items-center
           justify-between
           p-3
           text-white
           font-medium
           group
         "
      >
        <div
          className="
             flex
             justify-center
             items-center
             w-14
             h-14
             bg-blue-50
             rounded-full
             transition-all
             duration-300
             transform
             group-hover:rotate-12
           "
        >
          <svg
            width="30"
            height="30"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            className="
               stroke-current
               text-blue-500
               transform
               transition-transform
               duration-500
               ease-in-out
             "
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z"
            ></path>
          </svg>
        </div>
        <div className="text-right text-gray-600">
          <p className="text-2xl">557</p>
          <p>Orders</p>
        </div>
      </div>
      <div
        className="
           bg-white
           shadow-lg
           rounded-lg
           flex
           items-center
           justify-between
           p-3
           text-white
           font-medium
           group
         "
      >
        <div
          className="
             flex
             justify-center
             items-center
             w-14
             h-14
             bg-blue-100
             rounded-full
             transition-all
             duration-300
             transform
             group-hover:rotate-12
           "
        >
          <svg
            width="30"
            height="30"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            className="
               stroke-current
               text-blue-500
               dark:text-gray-800
               transform
               transition-transform
               duration-500
               ease-in-out
             "
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"
            ></path>
          </svg>
        </div>
        <div className="text-right text-gray-600">
          <p className="text-2xl">$11,257</p>
          <p>Sales</p>
        </div>
      </div>
      <div
        className="
           bg-white
           dark:bg-gray-800
           shadow-lg
           rounded-lg
           flex
           items-center
           justify-between
           p-3
           text-white
           font-medium
           group
         "
      >
        <div
          className="
             flex
             justify-center
             items-center
             w-14
             h-14
             bg-blue-100
             rounded-full
             transition-all
             duration-300
             transform
             group-hover:rotate-12
           "
        >
          <svg
            width="30"
            height="30"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            className="
               stroke-current
               text-blue-500
               transform
               transition-transform
               duration-500
               ease-in-out
             "
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
            ></path>
          </svg>
        </div>
        <div className="text-right text-gray-600">
          <p className="text-2xl">$75,257</p>
          <p>Balances</p>
        </div>
      </div>
    </div>
  );
};

export default StatusTransaction;
